ui/main_ui.go
=> update. 允许全角符号 resolve #9

README.md
Fix #28 by [this commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=go-musicfox-bin&id=dab3331cdc9d85080712d884cbfa078f0f136d63)
=> Fix libFLAC.so.8 dependency in AUR

README.md
go-musicfox已经被热心网友添加到Nixpkgs了。
=> 修改NixOS安装方式

pkg/ui/main_ui.go
=> add 歌曲列表菜单副标题内容超出显示宽度时滚动显示

utils/utils.go
修复Windows下载路径修改为其他盘符时报错：The system cannot move the file to a different disk drive
修复Windows下载报错 The process cannot access the file because it is being used by another process
=> 修复Windows下载失败的问题

pkg/lyric/lrc_timer.go
=> fix: 歌词到最后一行时拖动进度条无法正常更新

pkg/ui/player.go, utils/report.go
说不定能fix https://github.com/go-musicfox/go-musicfox/issues/102
待观察
=> add: 播放结束上报网易云

pkg/ui/lastfm.go
修复 #98 。请参照包内lastfm_auth文件自行添加 key 和 secret 。
另外顺手改一个typo。
=> 修复AUR包ldflags问题; 修复一个typo

.devenv/profile, README.md, flake.lock, flake.nix, nix/default.nix
- Provide development environment
- Provides nixos with a way to install the git version of this package
=> feat: Add flake support

.devenv/profile, .gitignore, flake.nix
=> fix: pr 110

utils/utils.go
fix https://github.com/go-musicfox/go-musicfox/issues/115
=> fix: 修复配置文件目录问题

pkg/player/mpd_player.go
=> feat: 向mpd发送歌曲信息

pkg/ui/main_ui.go, pkg/ui/player.go
=> fix: 在播放模式为单曲循环时手动切换歌曲

pkg/state_handler/mpris_player.go, pkg/state_handler/state_handler_linux.go
修复了提交[bcef056](https://github.com/go-musicfox/go-musicfox/commit/bcef056a0b23f2a0403609f4478cfd33087529b5)后无法构建的问题
=> fix: bcef056后无法构建

utils/utils.go
=> fix: #158 setting FLAC file will not halt; use tmp file

internal/ui/event_handler.go
=> fix iss203

internal/state_handler/state_handler.go, internal/state_handler/state_handler_darwin.go, internal/state_handler/state_handler_linux.go, internal/ui/player.go
=> fix(state_handler): update playing position every 200ms

internal/ui/player.go
=> fix: fix faulty position for MPRIS

README.md
=> Update readme for linux building and troubleshooting

internal/ui/menu_album_subsribe_list.go, internal/ui/menu_artists_subscribe_list.go
=> fix: subscribe_list unresponsive

deploy/musicfox.desktop
新建了linux下的桌面条目
名字和应用程序名字一样
要求icon满足xdg
=> 新建了desktop

utils/app/app.go
=> cache使用os.UserCacheDir

internal/ui/operate.go
=> fix: index out of range

go.mod, go.sum, internal/commands/netease.go, internal/configs/main.go, internal/configs/registry.go, utils/filex/embed/go-musicfox.ini, vendor/github.com/anhoder/foxful-cli/model/main.go, vendor/github.com/anhoder/foxful-cli/model/options.go, vendor/modules.txt
=> feat: support dynamic rows #219

utils/storagex/download.go
=> fix: reset file offset before parsing music tags

internal/commands/netease.go, internal/configs/lastfm.go, internal/configs/registry.go, internal/lastfm/api.go, internal/lastfm/track.go, internal/storage/lastfm_scrobble.go, internal/ui/lastfm.go, internal/ui/lastfm_auth.go, internal/ui/lastfm_res.go, internal/ui/netease.go, internal/ui/player.go, utils/filex/embed/go-musicfox.ini
=> refactor: lastfm scrobble

internal/ui/lastfm.go
支持临时切换上报状态（可提供给后续h手动触发队列上报）
Related to #405
=> feat(last.fm): support toggle scrobble status

internal/lastfm/track.go, internal/ui/lastfm.go
=> feat(last.fm): clean local scrobbles

README.md, internal/keybindings/keybindings.go, internal/ui/event_handler.go
=> fix: use action menu

cmd/musicfox.go, internal/commands/netease.go, internal/commands/options.go, internal/configs/main.go, internal/configs/registry.go, utils/filex/embed/go-musicfox.ini, utils/slogx/slog.go
=> feat(log): debug mode

internal/ui/player.go
=> fix: get song url

go.mod, go.sum, internal/ui/login_page.go, internal/ui/operate.go, utils/netease/report.go, vendor/github.com/go-musicfox/netease-music/service/login_cellphone_service.go, vendor/github.com/go-musicfox/netease-music/service/login_qr_service.go, vendor/github.com/go-musicfox/netease-music/service/logout_service.go, vendor/github.com/go-musicfox/netease-music/service/report_service.go, vendor/github.com/go-musicfox/netease-music/service/scrobble_service.go, vendor/github.com/go-musicfox/netease-music/util/common.go, vendor/github.com/go-musicfox/netease-music/util/cryto.go, vendor/github.com/go-musicfox/netease-music/util/request.go, vendor/modules.txt
1.同步上游依赖并显式处理错误
2.登出时调用退出登录api
=> 👌sync dependency && update services func

internal/commands/netease.go
=> fix(log): apply debug mode from config

internal/player/mpv_player.go
Correct the handling of the custom MPV binary path configuration.
=> Fix custom MPV binary path

.github/workflows/vendor-sync.yml
=> fix(ci): correct trigger branch to master for vendor sync
